### ISSUE TITLE
morpheus-java-sdk:0.3.1 not available

### ISSUE THREAD

**Issue by tadamhicks** [gomorpheus/morpheus-jenkins#1]
adamhicks  ~  morpheus-jenkins  gradle jpi
Download http://repo.jenkins-ci.org/releases/org/jenkins-ci/tools/gradle-jpi-plugin/0.22.0/gradle-jpi-plugin-0.22.0.pom
Download https://jcenter.bintray.com/net/java/sezpoz/sezpoz/1.12/sezpoz-1.12.pom
Download https://jcenter.bintray.com/net/java/sezpoz/pom/1.12/pom-1.12.pom
Download http://repo.jenkins-ci.org/releases/org/jenkins-ci/tools/gradle-jpi-plugin/0.22.0/gradle-jpi-plugin-0.22.0.jar
Download https://jcenter.bintray.com/net/java/sezpoz/sezpoz/1.12/sezpoz-1.12.jar
:localizer
:compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compileClasspath'.
> Could not find com.bertramlabs.plugins:morpheus-java-sdk:0.3.1.
  Searched in the following locations:
      file:/Users/adamhicks/.m2/repository/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.pom
      file:/Users/adamhicks/.m2/repository/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.jar
      https://repo1.maven.org/maven2/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.pom
      https://repo1.maven.org/maven2/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.jar
      https://repo.jenkins-ci.org/public/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.pom
      https://repo.jenkins-ci.org/public/com/bertramlabs/plugins/morpheus-java-sdk/0.3.1/morpheus-java-sdk-0.3.1.jar
  Required by:
      project :

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.317 secs

**Comment by will-districtnerds** [comment]
https://github.com/gomorpheus/morpheus-java-sdk is up to version 0.3.3. Run the gradle task publishToMavenLocal and you're good to go.
